class MarketingCampaign:
    ID_PREFIX = "MARKETING_CAMPAIGN:"
    LABEL = "marketing_campaign"

    class PropertyKey:
        UUID = "uuid"  # same as campaign_id
        NAME = "name"
        TAGS = "tags"
        SUBJECT = "subject"
        LIST = "list"
        SEND_TIME = "send_time"
        SEND_WEEKDAY = "send_weekday"
        TOTAL_RECIPIENTS = "total_recipients"
        UNIQUE_PLACED_ORDER = "unique_placed_order"
        PLACED_ORDER_RATE = "placed_order_rate"
        REVENUE = "revenue"
        UNIQUE_OPENS = "unique_opens"
        OPEN_RATE = "open_rate"
        TOTAL_OPENS = "total_opens"
        UNIQUE_CLICKS = "unique_clicks"
        CLICK_RATE = "click_rate"
        TOTAL_CLICKS = "total_clicks"
        UNSUBSCRIBES = "unsubscribes"
        SPAM_COMPLAINTS = "spam_complaints"
        SPAM_COMPLAINTS_RATE = "spam_complaints_rate"
        SUCCESSFUL_DELIVERIES = "successful_deliveries"
        BOUNCES = "bounces"
        BOUNCE_RATE = "bounce_rate"
        CAMPAIGN_ID = "campaign_id"
        CAMPAIGN_CHANNEL = "campaign_channel"
        INGESTION_TAG = "ingestion_tag"
        DATA_SOURCE = "data_source"
